const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
const SEARCH_MOVIE_COMPLETE = 'SEARCH_MOVIE_COMPLETE'

const SEARCH_MOVIE_BY_ID_START = 'SEARCH_MOVIE_BY_ID_START';
const SEARCH_MOVIE_BY_ID_ERROR = 'SEARCH_MOVIE_BY_ID_ERROR';
const SEARCH_MOVIE_BY_ID_COMPLETE = 'SEARCH_MOVIE_BY_ID_COMPLETE';

export {
    SEARCH_MOVIE_COMPLETE, SEARCH_MOVIE_ERROR, SEARCH_MOVIE_START, SEARCH_MOVIE_BY_ID_START,
    SEARCH_MOVIE_BY_ID_ERROR, SEARCH_MOVIE_BY_ID_COMPLETE
}